@BlogApi_HostAddress = https://localhost:7147

GET {{BlogApi_HostAddress}}/api/Posts/
Accept: application/json

###


POST {{BlogApi_HostAddress}}/api/Posts/
Content-Type: application/json

{
  "title": "eimai sti Magoula",
  "description": "string",
  "content": "string",
  "created": "2024-11-08T09:51:45.020Z",
  "updated": "2024-11-08T09:51:45.020Z"
}

###

GET {{BlogApi_HostAddress}}/api/Posts/1
Accept: application/json

###

DELETE {{BlogApi_HostAddress}}/api/Posts/1
Accept: application/json